services:
  dbquotes_backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_FILE: ./config/.env.backend
    ports:
      - "3000:3000"
    environment:
      - IN_DOCKER=true
      - DOCKER_MONGOURI=mongodb://mongo:27017/doublequotes
    depends_on:
      - mongo
      - redis

  mongo:
    image: bitnami/mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.4.0-alpine
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"

volumes:
  mongo-data:
  redis-data:
